%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%          Generated by MATLAB 23.2 and Fixed-Point Designer 23.2          %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function z = demInterpolate_wrapper_fixpt(demData,x,y)
    fm = get_fimath();
    demData_in = copyTo_demData_in( demData );
    x_in = fi( x, 0, 16, -3, fm );
    y_in = fi( y, 0, 16, -7, fm );
    [z_out] = demInterpolate_fixpt( demData_in, x_in, y_in );
    z = double( z_out );
end
function demData_in = copyTo_demData_in(demData)
    coder.inline( 'always' );
    fm = get_fimath();
    demData_in.X = fi( demData.X, 0, 19, 0, fm );
    demData_in.Y = fi( demData.Y, 0, 23, 0, fm );
    demData_in.Z = fi( demData.Z, 0, 16, 9, fm );
    demData_in.resolution = fi( demData.resolution, 0, 4, 0, fm );
    demData_in.xMin = fi( demData.xMin, 0, 19, 0, fm );
    demData_in.xMax = fi( demData.xMax, 0, 19, 0, fm );
    demData_in.yMin = fi( demData.yMin, 0, 23, 0, fm );
    demData_in.yMax = fi( demData.yMax, 0, 23, 0, fm );
    demData_in.type = demData.type;
    demData_in.minElevation = fi( demData.minElevation, 0, 16, 9, fm );
    demData_in.maxElevation = fi( demData.maxElevation, 0, 16, 9, fm );
    demData_in.meanElevation = fi( demData.meanElevation, 0, 16, 9, fm );
    demData_in.stdElevation = fi( demData.stdElevation, 0, 16, 12, fm );
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
